server:
  port: 8000 #??????
  servlet:
    encoding:
      force-response: true

spring:
  main:
    allow-circular-references: true
  application:
    name: Druid
  datasource:
    url: jdbc:mysql://api.yuanzhangzcc.com:3306/??????useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
#??sql????
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  mapper-locations: 'classpath: mapper/*.xml'
